version: "3"

services:
  # Servicio web, el primero
  web:
    image: sermorap/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          # memory: 300M  # Memoria comentada por ahora
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"   # Puerto mapeado para acceso web

  # Servicio de base de datos MongoDB
  mongo:
    image: sermorap/p2gps:db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.15"
          # memory: 200M  # Memoria comentada por ahora
      restart_policy:
        condition: on-failure
    ports:
      - "28017:28017"  # Puerto para administración de MongoDB
      - "27017:27017"  # Puerto principal de MongoDB
    volumes:
      - "db-data:/data/db"  # Persistencia de datos en el volumen db-data

  # Servicio backend
  order:
    image: sermorap/p2gps:order
    depends_on:
      - "mongo"  # Dependencia de MongoDB para el backend
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          # memory: 500M  # Memoria comentada por ahora
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"   # Puerto para servicio backend

# Volúmenes para persistencia de datos
volumes:
  db-data:
